package com.fanx.shardingspheredemo.entity;

import java.math.BigDecimal;

public class OrderItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item.id
     *
     * @mbg.generated Wed Dec 29 21:34:58 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item.order_id
     *
     * @mbg.generated Wed Dec 29 21:34:58 CST 2021
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item.product_id
     *
     * @mbg.generated Wed Dec 29 21:34:58 CST 2021
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item.product_num
     *
     * @mbg.generated Wed Dec 29 21:34:58 CST 2021
     */
    private Integer productNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item.sold_price
     *
     * @mbg.generated Wed Dec 29 21:34:58 CST 2021
     */
    private BigDecimal soldPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item.user_id
     *
     * @mbg.generated Wed Dec 29 21:34:58 CST 2021
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.id
     *
     * @return the value of t_order_item.id
     *
     * @mbg.generated Wed Dec 29 21:34:58 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.id
     *
     * @param id the value for t_order_item.id
     *
     * @mbg.generated Wed Dec 29 21:34:58 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.order_id
     *
     * @return the value of t_order_item.order_id
     *
     * @mbg.generated Wed Dec 29 21:34:58 CST 2021
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.order_id
     *
     * @param orderId the value for t_order_item.order_id
     *
     * @mbg.generated Wed Dec 29 21:34:58 CST 2021
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.product_id
     *
     * @return the value of t_order_item.product_id
     *
     * @mbg.generated Wed Dec 29 21:34:58 CST 2021
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.product_id
     *
     * @param productId the value for t_order_item.product_id
     *
     * @mbg.generated Wed Dec 29 21:34:58 CST 2021
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.product_num
     *
     * @return the value of t_order_item.product_num
     *
     * @mbg.generated Wed Dec 29 21:34:58 CST 2021
     */
    public Integer getProductNum() {
        return productNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.product_num
     *
     * @param productNum the value for t_order_item.product_num
     *
     * @mbg.generated Wed Dec 29 21:34:58 CST 2021
     */
    public void setProductNum(Integer productNum) {
        this.productNum = productNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.sold_price
     *
     * @return the value of t_order_item.sold_price
     *
     * @mbg.generated Wed Dec 29 21:34:58 CST 2021
     */
    public BigDecimal getSoldPrice() {
        return soldPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.sold_price
     *
     * @param soldPrice the value for t_order_item.sold_price
     *
     * @mbg.generated Wed Dec 29 21:34:58 CST 2021
     */
    public void setSoldPrice(BigDecimal soldPrice) {
        this.soldPrice = soldPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.user_id
     *
     * @return the value of t_order_item.user_id
     *
     * @mbg.generated Wed Dec 29 21:34:58 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.user_id
     *
     * @param userId the value for t_order_item.user_id
     *
     * @mbg.generated Wed Dec 29 21:34:58 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}