package com.fanx.xa.atomikos.mapper.db162;

import com.fanx.xa.atomikos.entity.Xa162;
import com.fanx.xa.atomikos.entity.Xa162Example;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface Xa162Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_162
     *
     * @mbg.generated Tue Jan 04 16:30:18 CST 2022
     */
    long countByExample(Xa162Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_162
     *
     * @mbg.generated Tue Jan 04 16:30:18 CST 2022
     */
    int deleteByExample(Xa162Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_162
     *
     * @mbg.generated Tue Jan 04 16:30:18 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_162
     *
     * @mbg.generated Tue Jan 04 16:30:18 CST 2022
     */
    int insert(Xa162 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_162
     *
     * @mbg.generated Tue Jan 04 16:30:18 CST 2022
     */
    int insertSelective(Xa162 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_162
     *
     * @mbg.generated Tue Jan 04 16:30:18 CST 2022
     */
    List<Xa162> selectByExample(Xa162Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_162
     *
     * @mbg.generated Tue Jan 04 16:30:18 CST 2022
     */
    Xa162 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_162
     *
     * @mbg.generated Tue Jan 04 16:30:18 CST 2022
     */
    int updateByExampleSelective(@Param("record") Xa162 record, @Param("example") Xa162Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_162
     *
     * @mbg.generated Tue Jan 04 16:30:18 CST 2022
     */
    int updateByExample(@Param("record") Xa162 record, @Param("example") Xa162Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_162
     *
     * @mbg.generated Tue Jan 04 16:30:18 CST 2022
     */
    int updateByPrimaryKeySelective(Xa162 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_162
     *
     * @mbg.generated Tue Jan 04 16:30:18 CST 2022
     */
    int updateByPrimaryKey(Xa162 record);
}