package com.fanx.xa.atomikos.entity;

public class Xa162 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xa_162.id
     *
     * @mbg.generated Tue Jan 04 16:30:18 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xa_162.name
     *
     * @mbg.generated Tue Jan 04 16:30:18 CST 2022
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xa_162.id
     *
     * @return the value of xa_162.id
     *
     * @mbg.generated Tue Jan 04 16:30:18 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xa_162.id
     *
     * @param id the value for xa_162.id
     *
     * @mbg.generated Tue Jan 04 16:30:18 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xa_162.name
     *
     * @return the value of xa_162.name
     *
     * @mbg.generated Tue Jan 04 16:30:18 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xa_162.name
     *
     * @param name the value for xa_162.name
     *
     * @mbg.generated Tue Jan 04 16:30:18 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}